const fs = require('fs');
const path = require('path');

// Helper function to build university entries
function createUni({
  id,
  name,
  shortName,
  country,
  city,
  continent,
  worldRanking = null,
  qsRanking = null,
  theRanking = null,
  type = "Public",
  website,
  logo = "",
  heroImage = "",
  acceptanceRate = null,
  studentPopulation = null,
  internationalStudents = null,
  founded = null,
  tuitionIntl = null,
  tuitionDom = null,
  currency = "USD",
  livingCost = null,
  livingCurrency = "USD",
  appFee = null,
  appFeeCurrency = "USD",
  earlyDeadline = null,
  regularDeadline = null,
  springDeadline = null,
  ielts = null,
  toefl = null,
  duolingo = null,
  minimumGPA = null,
  popularMajors = [],
  availableDegrees = ["Bachelor", "Master", "PhD"],
  scholarshipsAvailable = true,
  description = "",
  campusType = "Urban",
  climate = "Temperate",
  employmentRate = null,
  facebook = "",
  instagram = "",
  linkedin = "",
  youtube = ""
}) {
  const cleanId = id || name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
  const domain = website ? website.replace(/^https?:\/\/(www\.)?/, '').split('/')[0] : '';
  
  return {
    id: cleanId,
    name,
    shortName: shortName || name,
    country,
    city,
    continent,
    worldRanking: worldRanking || qsRanking || null,
    qsRanking: qsRanking || worldRanking || null,
    theRanking: theRanking || null,
    type,
    website,
    logo: logo || (domain ? `https://logo.clearbit.com/${domain}` : ""),
    heroImage: heroImage || "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1200&q=80",
    acceptanceRate: acceptanceRate !== null ? acceptanceRate : null,
    studentPopulation: studentPopulation !== null ? studentPopulation : null,
    internationalStudents: internationalStudents !== null ? internationalStudents : null,
    founded: founded !== null ? founded : null,
    tuition: {
      international: tuitionIntl !== null ? tuitionIntl : null,
      domestic: tuitionDom !== null ? tuitionDom : null,
      currency: currency || "USD"
    },
    livingCostPerYear: {
      amount: livingCost !== null ? livingCost : null,
      currency: livingCurrency || currency || "USD"
    },
    applicationFee: {
      amount: appFee !== null ? appFee : null,
      currency: appFeeCurrency || currency || "USD"
    },
    applicationDeadlines: {
      earlyAction: earlyDeadline !== undefined ? earlyDeadline : null,
      regularDecision: regularDeadline !== undefined ? regularDeadline : null,
      spring: springDeadline !== undefined ? springDeadline : null
    },
    languageRequirements: {
      ielts: ielts !== null ? ielts : null,
      toefl: toefl !== null ? toefl : null,
      duolingo: duolingo !== null ? duolingo : null
    },
    minimumGPA: minimumGPA !== null ? minimumGPA : null,
    popularMajors: Array.isArray(popularMajors) ? popularMajors : [],
    availableDegrees: Array.isArray(availableDegrees) ? availableDegrees : ["Bachelor", "Master", "PhD"],
    scholarshipsAvailable: scholarshipsAvailable !== undefined ? scholarshipsAvailable : true,
    description: description || `${name} is a globally recognized institution situated in ${city}, ${country}, offering comprehensive academic and research programs.`,
    campusType: campusType || "Urban",
    climate: climate || "Temperate",
    employmentRate: employmentRate !== null ? employmentRate : null,
    officialSocials: {
      facebook: facebook || "",
      instagram: instagram || "",
      linkedin: linkedin || "",
      youtube: youtube || ""
    }
  };
}

const universities = [];

// ==========================================
// NORTH AMERICA (USA, Canada, Mexico)
// ==========================================

// --- USA ---
universities.push(
  createUni({
    id: "mit",
    name: "Massachusetts Institute of Technology",
    shortName: "MIT",
    country: "United States",
    city: "Cambridge",
    continent: "North America",
    worldRanking: 1,
    qsRanking: 1,
    theRanking: 2,
    type: "Private",
    website: "https://www.mit.edu",
    heroImage: "https://images.unsplash.com/photo-1564981797816-1043664bf78d?auto=format&fit=crop&w=1200&q=80",
    acceptanceRate: 4.0,
    studentPopulation: 11934,
    internationalStudents: 3800,
    founded: 1861,
    tuitionIntl: 61990,
    tuitionDom: 61990,
    currency: "USD",
    livingCost: 19800,
    appFee: 75,
    earlyDeadline: "November 1",
    regularDeadline: "January 1",
    springDeadline: null,
    ielts: 7.5,
    toefl: 100,
    duolingo: 135,
    minimumGPA: 3.9,
    popularMajors: ["Computer Science", "Mechanical Engineering", "Physics", "Mathematics", "Aeronautics"],
    description: "The Massachusetts Institute of Technology is a world-renowned private research university in Cambridge, Massachusetts, known for its rigorous STEM education and cutting-edge research.",
    campusType: "Urban",
    climate: "Temperate Continental",
    employmentRate: 96.0
  }),
  createUni({
    id: "stanford",
    name: "Stanford University",
    shortName: "Stanford",
    country: "United States",
    city: "Stanford",
    continent: "North America",
    worldRanking: 2,
    qsRanking: 2,
    theRanking: 3,
    type: "Private",
    website: "https://www.stanford.edu",
    heroImage: "https://images.unsplash.com/photo-1583321500900-82807e458f3c?auto=format&fit=crop&w=1200&q=80",
    acceptanceRate: 3.9,
    studentPopulation: 17326,
    internationalStudents: 3900,
    founded: 1885,
    tuitionIntl: 62480,
    tuitionDom: 62480,
    currency: "USD",
    livingCost: 20500,
    appFee: 90,
    earlyDeadline: "November 1",
    regularDeadline: "January 5",
    springDeadline: null,
    ielts: 7.5,
    toefl: 100,
    duolingo: 135,
    minimumGPA: 3.95,
    popularMajors: ["Computer Science", "Human Biology", "Econometrics", "Engineering", "Psychology"],
    description: "Located in California's Silicon Valley, Stanford University is one of the world's leading teaching and research institutions with a tradition of innovation.",
    campusType: "Suburban",
    climate: "Mediterranean",
    employmentRate: 95.5
  }),
  createUni({
    id: "harvard",
    name: "Harvard University",
    shortName: "Harvard",
    country: "United States",
    city: "Cambridge",
    continent: "North America",
    worldRanking: 4,
    qsRanking: 4,
    theRanking: 2,
    type: "Private",
    website: "https://www.harvard.edu",
    heroImage: "https://images.unsplash.com/photo-1607237138185-eedd996e5b09?auto=format&fit=crop&w=1200&q=80",
    acceptanceRate: 3.4,
    studentPopulation: 25261,
    internationalStudents: 6100,
    founded: 1636,
    tuitionIntl: 59076,
    tuitionDom: 59076,
    currency: "USD",
    livingCost: 20100,
    appFee: 85,
    earlyDeadline: "November 1",
    regularDeadline: "January 1",
    springDeadline: null,
    ielts: 7.5,
    toefl: 100,
    duolingo: 135,
    minimumGPA: 3.9,
    popularMajors: ["Economics", "Computer Science", "Government", "Applied Mathematics", "Neuroscience"],
    description: "Established in 1636, Harvard University is the oldest institution of higher learning in the United States and among the most prestigious globally.",
    campusType: "Urban",
    climate: "Temperate Continental",
    employmentRate: 96.2
  }),
  createUni({
    id: "caltech",
    name: "California Institute of Technology",
    shortName: "Caltech",
    country: "United States",
    city: "Pasadena",
    continent: "North America",
    worldRanking: 7,
    qsRanking: 7,
    theRanking: 6,
    type: "Private",
    website: "https://www.caltech.edu",
    heroImage: "https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1200&q=80",
    acceptanceRate: 2.7,
    studentPopulation: 2397,
    internationalStudents: 800,
    founded: 1891,
    tuitionIntl: 60864,
    tuitionDom: 60864,
    currency: "USD",
    livingCost: 18600,
    appFee: 75,
    earlyDeadline: "November 1",
    regularDeadline: "January 3",
    springDeadline: null,
    ielts: 7.5,
    toefl: 100,
    duolingo: 135,
    minimumGPA: 3.9,
    popularMajors: ["Computer Science", "Physics", "Electrical Engineering", "Bioengineering", "Mathematics"],
    description: "Caltech is a world-renowned science and engineering institute known for its high-impact research, small student body, and management of NASA's Jet Propulsion Laboratory.",
    campusType: "Suburban",
    climate: "Mediterranean",
    employmentRate: 94.8
  }),
  createUni({
    id: "princeton",
    name: "Princeton University",
    shortName: "Princeton",
    country: "United States",
    city: "Princeton",
    continent: "North America",
    worldRanking: 6,
    qsRanking: 6,
    theRanking: 7,
    type: "Private",
    website: "https://www.princeton.edu",
    heroImage: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1200&q=80",
    acceptanceRate: 4.4,
    studentPopulation: 8475,
    internationalStudents: 1900,
    founded: 1746,
    tuitionIntl: 59710,
    tuitionDom: 59710,
    currency: "USD",
    livingCost: 18600,
    appFee: 75,
    earlyDeadline: "November 1",
    regularDeadline: "January 1",
    springDeadline: null,
    ielts: 7.5,
    toefl: 100,
    duolingo: 135,
    minimumGPA: 3.9,
    popularMajors: ["Computer Science", "Public Policy", "Economics", "History", "Operations Research"],
    description: "Princeton University is a private Ivy League research university providing undergraduate and graduate instruction in the humanities, social sciences, natural sciences, and engineering.",
    campusType: "Suburban",
    climate: "Humid Subtropical",
    employmentRate: 95.8
  })
);

console.log("Building North America...");
